### ISSUE TITLE
syntax error when running the module

### ISSUE THREAD

**Issue by csmaxx** [joelspadin/zmk-locale-generator#3]
I have cloned the repo but get a syntax error when I run the following

`python3 -m zmk_locale_generator DA cldr/keyboards/windows/da-t-k0-windows.xml --out da_keys.h
`

I get the following error:

```

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/csmax/temp/zmk-locale-generator/zmk_locale_generator/__init__.py", line 1, in <module>
    from .generator import LayoutHeaderGenerator as LayoutHeaderGenerator
  File "/home/csmax/temp/zmk-locale-generator/zmk_locale_generator/generator.py", line 85
    match self.zmk_keys[name]:
          ^
SyntaxError: invalid syntax

```

My system is:
MacOS Venture 13.4.1
Python 3.9.6

**Comment by joelspadin** [comment]
Python 3.11 is required.
