### ISSUE TITLE
Error when trying to generate Headers

### ISSUE THREAD

**Issue by worms19** [joelspadin/zmk-locale-generator#5]
hi , 

I tried to generate manually a header myself .

and this is the error i got : 

`python3 -m zmk_locale_generator FR cldr/fr-mac.xml --out fr-mac.h
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/damien/dev/zmk-locale-generator/zmk_locale_generator/__main__.py", line 41, in <module>
    main()
  File "/Users/damien/dev/zmk-locale-generator/zmk_locale_generator/__main__.py", line 35, in main
    generate(infile, outfile)
  File "/Users/damien/dev/zmk-locale-generator/zmk_locale_generator/__main__.py", line 27, in generate
    generator = LayoutHeaderGenerator(args.zmk)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/damien/dev/zmk-locale-generator/zmk_locale_generator/generator.py", line 29, in __init__
    self.zmk_keys = parse_zmk_keys(zmk_path)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/damien/dev/zmk-locale-generator/zmk_locale_generator/keys.py", line 55, in parse_zmk_keys
    with keys_h_path.open("r", encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/damien/dev/zmk-locale-generator/zmk_locale_generator/keys.h'`

i'm not familiar with pyton any idea on why i would get this error ??

Thanks a lot

**Comment by joelspadin** [comment]
You likely didn't check out the submodules that contain some of the needed files. Try running this first:
```
git submodule update --init --recursive
```

I should add this to the readme.

**Comment by worms19** [comment]
it worked thank you very much
