### ISSUE TITLE
Error by usage of zmk_locale_generator

### ISSUE THREAD

**Issue by jschmahl** [joelspadin/zmk-locale-generator#9]
Hi.

I'm using:
- MacOS Sonoma 14.4.1
- Python 3.9.6

After a successful setup I tried to generate a new Header the python script prompted me:

`python3 -m zmk_locale_generator DE cldr/keyboards/osx/de-t-k0-osx.xml --out keys_de_osx.h
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/Users/***/developer/zmk-locale-generator/zmk_locale_generator/__init__.py", line 1, in <module>
    from .generator import LayoutHeaderGenerator as LayoutHeaderGenerator
  File "/Users/***/developer/zmk-locale-generator/zmk_locale_generator/generator.py", line 85
    match self.zmk_keys[name]:
          ^
SyntaxError: invalid syntax
`

sadly I'm not firm in python.

**Comment by caksoylar** [comment]
I think this was resolved in https://discord.com/channels/719497620560543766/719909884769992755/1232456225149423677

**Comment by joelspadin** [comment]
Yes. Python 3.10 or newer is required.
